export const SkillsConstants={
    SKILL_REQUEST:"SKILL_REQUEST",
    SKILL_SUCCESS:"SKILL_SUCCESS",
    SKILL_FAILURE:"SKILL_FAILURE",
}
export const initialDataConstants={
    DATA_REQUEST:"DATA_REQUEST",
    DATA_SUCCESS:"DATA_SUCCESS",
    DATA_FAILURE:"DATA_FAILURE",
}
export const authConstants={
    LOGIN_REQUEST:"LOGIN_REQUEST",
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGIN_FAILURE:'LOGIN_FAILURE',
    LOGOUT_REQUEST:'LOGOUT_REQUEST',
    LOGOUT_SUCCESS:'LOGOUT_SUCCESS',
    LOGOUT_FAILURE:'LOGOUT_FAILURE'
}